server:
  port: 8085
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: oracleatp
  datasource:
    url: jdbc:oracle:thin:@atpprueba0001_medium?TNS_ADMIN=D:/Wallets/atpprueba0001
    username: demo_user
    password: Valle_Grande@2023
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true

oracle:
  jdbc:
    fanEnabled: false